name: Deploy Angular App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install Dependencies
        run: npm install --force

      - name: Build Angular App
        run: ng build --configuration=production

      - name: Upload Build to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance host
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_PRIVATE_KEY }}  
          source: 'dist/e-store-app/' 
          target: '/var/www/html/eStore-app/dist'  
